-- ============================================================
-- SCHEMA DO BANCO DE DADOS SUPABASE (PostgreSQL)
-- Vitrine Online & Painel Administrativo de Vendas
-- Arquitetura: VENDEDORA -> ESTOJO -> PRODUTOS -> VENDAS
-- ============================================================
-- Execute este script no SQL Editor do seu projeto Supabase:
-- Execute este script no SQL Editor do Supabase:
-- https://app.supabase.com -> Selecione seu projeto -> SQL Editor -> New Query

-- 1. TABELA DE VENDEDORAS
CREATE TABLE IF NOT EXISTS public.vendedoras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    whatsapp VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Ativo' CHECK (status IN ('Ativo', 'Inativo')),
-- 1. TABELA DE VENDEDORAS (sellers)
CREATE TABLE IF NOT EXISTS public.sellers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT true,
    foto_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. TABELA DE PRODUTOS
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) UNIQUE,
    nome VARCHAR(255) NOT NULL,
-- 2. TABELA DE ESTOJOS (cases)
CREATE TABLE IF NOT EXISTS public.cases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    descricao TEXT,
    seller_id UUID REFERENCES public.sellers(id) ON DELETE SET NULL,
    ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. TABELA DE CATEGORIAS (categories)
CREATE TABLE IF NOT EXISTS public.categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. TABELA DE PRODUTOS (products)
CREATE TABLE IF NOT EXISTS public.products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo TEXT UNIQUE,
    nome TEXT NOT NULL,
    descricao TEXT,
    categoria TEXT NOT NULL DEFAULT 'Outros',
    preco NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    categoria VARCHAR(50) NOT NULL DEFAULT 'Outros',
    case_id UUID REFERENCES public.cases(id) ON DELETE SET NULL,
    imagem_url TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'Disponível' CHECK (status IN ('Disponível', 'Indisponível', 'Vendido')),
    estoque INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    status TEXT NOT NULL DEFAULT 'Disponível' CHECK (status IN ('Disponível', 'Indisponível', 'Vendido')),
    ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. TABELA DE PEDIDOS (VENDAS)
CREATE TABLE IF NOT EXISTS public.pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido VARCHAR(50) UNIQUE NOT NULL,
    cliente_nome VARCHAR(150) NOT NULL,
    cliente_telefone VARCHAR(30),
-- 5. TABELA DE VENDAS / PEDIDOS (sales)
CREATE TABLE IF NOT EXISTS public.sales (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero_venda TEXT UNIQUE NOT NULL,
    cliente_nome TEXT NOT NULL,
    cliente_telefone TEXT,
    observacoes TEXT,
    vendedora_id BIGINT REFERENCES public.vendedoras(id) ON DELETE SET NULL,
    vendedora_nome VARCHAR(100),
    seller_id UUID REFERENCES public.sellers(id) ON DELETE SET NULL,
    forma_pagamento TEXT NOT NULL DEFAULT 'WhatsApp / A Combinar',
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(30) NOT NULL DEFAULT 'Pendente' CHECK (status IN ('Pendente', 'Concluído', 'Cancelado')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    status TEXT NOT NULL DEFAULT 'Pendente' CHECK (status IN ('Pendente', 'Concluída', 'Cancelada')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. ITENS DO PEDIDO
CREATE TABLE IF NOT EXISTS public.pedido_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT REFERENCES public.pedidos(id) ON DELETE CASCADE NOT NULL,
    produto_id BIGINT REFERENCES public.produtos(id) ON DELETE SET NULL,
    produto_nome VARCHAR(255) NOT NULL,
-- 6. ITENS DA VENDA COM ORIGEM DE ESTOJO (sale_items)
CREATE TABLE IF NOT EXISTS public.sale_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sale_id UUID REFERENCES public.sales(id) ON DELETE CASCADE NOT NULL,
    product_id UUID REFERENCES public.products(id) ON DELETE SET NULL,
    case_id UUID REFERENCES public.cases(id) ON DELETE SET NULL,
    seller_id UUID REFERENCES public.sellers(id) ON DELETE SET NULL,
    produto_nome TEXT NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    subtotal NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 7. TABELA DE FECHAMENTO DE ESTOJO (case_closings)
CREATE TABLE IF NOT EXISTS public.case_closings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id UUID REFERENCES public.cases(id) ON DELETE CASCADE NOT NULL,
    seller_id UUID REFERENCES public.sellers(id) ON DELETE SET NULL,
    data_inicial TIMESTAMPTZ NOT NULL,
    data_final TIMESTAMPTZ NOT NULL,
    total_pecas_iniciais INTEGER NOT NULL DEFAULT 0,
    total_pecas_vendidas INTEGER NOT NULL DEFAULT 0,
    total_pecas_restantes INTEGER NOT NULL DEFAULT 0,
    valor_total_vendido NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    comissao_vendedora_pct NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    valor_comissao_vendedora NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    comissao_proprietaria_pct NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    valor_repasse NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    observacoes TEXT,
    status TEXT NOT NULL DEFAULT 'Fechado',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ============================================================
-- HABILITAR ROW LEVEL SECURITY (RLS)
-- ============================================================
ALTER TABLE public.vendedoras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_itens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sellers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.case_closings ENABLE ROW LEVEL SECURITY;

-- Políticas para Acesso Público (Vitrine / Anon)
-- Qualquer cliente pode ver vendedoras ativas
CREATE POLICY "Permitir leitura pública de vendedoras ativas" 
ON public.vendedoras FOR SELECT 
TO anon, authenticated 
USING (status = 'Ativo' OR auth.role() = 'authenticated');
-- Políticas Públicas (Vitrine / Anon)
CREATE POLICY "Leitura pública de vendedoras ativas" ON public.sellers FOR SELECT TO anon, authenticated USING (ativo = true OR auth.role() = 'authenticated');
CREATE POLICY "Leitura pública de estojos ativos" ON public.cases FOR SELECT TO anon, authenticated USING (ativo = true OR auth.role() = 'authenticated');
CREATE POLICY "Leitura pública de categorias ativas" ON public.categories FOR SELECT TO anon, authenticated USING (ativo = true OR auth.role() = 'authenticated');
CREATE POLICY "Leitura pública de produtos disponíveis" ON public.products FOR SELECT TO anon, authenticated USING (ativo = true);

-- Qualquer cliente pode visualizar produtos
CREATE POLICY "Permitir leitura pública de produtos" 
ON public.produtos FOR SELECT 
TO anon, authenticated 
USING (true);
CREATE POLICY "Inserção pública de vendas pelo checkout" ON public.sales FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Inserção pública de itens de venda" ON public.sale_items FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Clientes podem criar pedidos e itens ao finalizar compra pelo WhatsApp
CREATE POLICY "Permitir inserção pública de pedidos" 
ON public.pedidos FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);
-- Políticas Administrativas (Total Acesso para autenticados)
CREATE POLICY "Acesso total admin sellers" ON public.sellers FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total admin cases" ON public.cases FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total admin categories" ON public.categories FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total admin products" ON public.products FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total admin sales" ON public.sales FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total admin sale_items" ON public.sale_items FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total admin case_closings" ON public.case_closings FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Permitir inserção pública de itens de pedidos" 
ON public.pedido_itens FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Políticas para Administrador Autenticado (Acesso Total)
CREATE POLICY "Acesso total de administradores em vendedoras" 
ON public.vendedoras FOR ALL 
TO authenticated 
USING (true) WITH CHECK (true);

CREATE POLICY "Acesso total de administradores em produtos" 
ON public.produtos FOR ALL 
TO authenticated 
USING (true) WITH CHECK (true);

CREATE POLICY "Acesso total de administradores em pedidos" 
ON public.pedidos FOR ALL 
TO authenticated 
USING (true) WITH CHECK (true);

CREATE POLICY "Acesso total de administradores em pedido_itens" 
ON public.pedido_itens FOR ALL 
TO authenticated 
USING (true) WITH CHECK (true);

-- ============================================================
-- CRIAÇÃO DO BUCKET DE STORAGE (PRODUTOS)
-- BUCKET DE STORAGE (PRODUTOS)
-- ============================================================
INSERT INTO storage.buckets (id, name, public) 
VALUES ('produtos', 'produtos', true)
ON CONFLICT (id) DO NOTHING;

-- Permitir visualização pública das imagens do bucket produtos
CREATE POLICY "Visualização pública de imagens no bucket produtos" 
ON storage.objects FOR SELECT 
TO public 
USING (bucket_id = 'produtos');
CREATE POLICY "Visualização pública de imagens" ON storage.objects FOR SELECT TO public USING (bucket_id = 'produtos');
CREATE POLICY "Upload para autenticados" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'produtos');
CREATE POLICY "Edição e exclusão para autenticados" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'produtos');
CREATE POLICY "Deleção para autenticados" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'produtos');

-- Permitir upload/atualização/remoção para usuários autenticados no bucket produtos
CREATE POLICY "Upload permitido para autenticados no bucket produtos" 
ON storage.objects FOR INSERT 
TO authenticated 
WITH CHECK (bucket_id = 'produtos');

CREATE POLICY "Edição e exclusão de imagens para autenticados" 
ON storage.objects FOR UPDATE 
TO authenticated 
USING (bucket_id = 'produtos');

CREATE POLICY "Exclusão de imagens para autenticados" 
ON storage.objects FOR DELETE 
TO authenticated 
USING (bucket_id = 'produtos');

-- ============================================================
-- DADOS INICIAIS DE EXEMPLO (SEED DATA)
-- DADOS INICIAIS (SEED DATA)
-- ============================================================

-- Vendedoras Iniciais
INSERT INTO public.vendedoras (nome, whatsapp, status, foto_url) VALUES
('Gaby', '5567999887766', 'Ativo', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80'),
('Vanessa', '5567988776655', 'Ativo', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80')
ON CONFLICT DO NOTHING;
-- Vendedoras
INSERT INTO public.sellers (id, nome, whatsapp, ativo, foto_url) VALUES
('b1000000-0000-0000-0000-000000000001', 'Gaby', '5567999887766', true, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80'),
('b2000000-0000-0000-0000-000000000002', 'Vanessa', '5567988776655', true, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80')
ON CONFLICT (id) DO NOTHING;

-- Produtos Iniciais
INSERT INTO public.produtos (codigo, nome, descricao, preco, categoria, imagem_url, status, estoque) VALUES
('BR-001', 'Brinco Dourado Argola Elegance', 'Brinco argola clássica banhada a ouro 18k com acabamento polido de alto brilho.', 35.00, 'Brincos', 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80', 'Disponível', 5),
('COL-002', 'Colar Coração Zircônia Cristal', 'Colar delicado com pingente de coração em zircônia cravejada, banhado a ouro 18k.', 89.00, 'Colares', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80', 'Disponível', 3),
('PUL-003', 'Pulseira Dourada Elos Cartier', 'Pulseira feminina com elos estilo Cartier e fecho boia seguro e refinado.', 45.00, 'Pulseiras', 'https://images.unsplash.com/photo-1611591475883-9b932bb8269e?w=600&auto=format&fit=crop&q=80', 'Disponível', 8),
('ANE-004', 'Anel Solitário Cristal Luxo', 'Anel solitário elegante com pedra central brilhante lapidação navete.', 69.90, 'Anéis', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80', 'Disponível', 4),
('PIN-005', 'Pingente Estrela Radiante', 'Pingente delicado em formato de estrela com micropavê de zircônias.', 39.00, 'Pingentes', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80', 'Disponível', 6),
('BR-006', 'Brinco Pérola Natural Barroca', 'Par de brincos clássicos com pérola natural e base dourada antialérgica.', 55.00, 'Brincos', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=600&auto=format&fit=crop&q=80', 'Vendido', 0)
ON CONFLICT DO NOTHING;
-- Estojos vinculados às vendedoras
INSERT INTO public.cases (id, nome, descricao, seller_id, ativo) VALUES
('c1000000-0000-0000-0000-000000000001', 'Estojo Gaby', 'Estojo de semijoias finas sob responsabilidade da Gaby.', 'b1000000-0000-0000-0000-000000000001', true),
('c2000000-0000-0000-0000-000000000002', 'Estojo Vanessa', 'Estojo de lançamentos e colares de luxo sob responsabilidade da Vanessa.', 'b2000000-0000-0000-0000-000000000002', true),
('c3000000-0000-0000-0000-000000000003', 'Estojo Mostruário Loja', 'Peças de pronta entrega do mostruário físico da boutique.', 'b1000000-0000-0000-0000-000000000001', true)
ON CONFLICT (id) DO NOTHING;

-- Categorias
INSERT INTO public.categories (id, nome, ativo) VALUES
('d1000000-0000-0000-0000-000000000001', 'Brincos', true),
('d2000000-0000-0000-0000-000000000002', 'Colares', true),
('d3000000-0000-0000-0000-000000000003', 'Pulseiras', true),
('d4000000-0000-0000-0000-000000000004', 'Anéis', true),
('d5000000-0000-0000-0000-000000000005', 'Pingentes', true),
('d6000000-0000-0000-0000-000000000006', 'Outros', true)
ON CONFLICT (id) DO NOTHING;

-- Produtos vinculados obrigatoriamente a um estojo
INSERT INTO public.products (id, codigo, nome, descricao, categoria, preco, case_id, imagem_url, estoque, status, ativo) VALUES
('e1000000-0000-0000-0000-000000000001', 'BR-001', 'Brinco Dourado Argola Elegance', 'Brinco argola clássica banhada a ouro 18k com acabamento polido de alto brilho.', 'Brincos', 35.00, 'c1000000-0000-0000-0000-000000000001', 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80', 5, 'Disponível', true),
('e2000000-0000-0000-0000-000000000002', 'COL-002', 'Colar Coração Zircônia Cristal', 'Colar delicado com pingente de coração em zircônia cravejada, banhado a ouro 18k.', 'Colares', 89.00, 'c2000000-0000-0000-0000-000000000002', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80', 3, 'Disponível', true),
('e3000000-0000-0000-0000-000000000003', 'PUL-003', 'Pulseira Dourada Elos Cartier', 'Pulseira feminina com elos estilo Cartier e fecho boia seguro e refinado.', 'Pulseiras', 45.00, 'c1000000-0000-0000-0000-000000000001', 'https://images.unsplash.com/photo-1611591475883-9b932bb8269e?w=600&auto=format&fit=crop&q=80', 8, 'Disponível', true),
('e4000000-0000-0000-0000-000000000004', 'ANE-004', 'Anel Solitário Cristal Luxo', 'Anel solitário elegante com pedra central brilhante lapidação navete.', 'Anéis', 69.90, 'c2000000-0000-0000-0000-000000000002', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80', 4, 'Disponível', true),
('e5000000-0000-0000-0000-000000000005', 'PIN-005', 'Pingente Estrela Radiante', 'Pingente delicado em formato de estrela com micropavê de zircônias.', 'Pingentes', 39.00, 'c3000000-0000-0000-0000-000000000003', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80', 6, 'Disponível', true)
ON CONFLICT (id) DO NOTHING;
